# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\专业实训\程序实现\news.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import dfshow
import news_sql
import updata_news
import pandas as pd
from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(880, 90, 91, 31))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 9pt \"思源黑体 CN Medium\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 52, 135, 255), stop:1 rgba(18, 63, 149, 255));")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 90, 711, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 471, 41))
        self.label.setStyleSheet("font: 25 16pt \"思源宋体 CN Light\";\n"
"color: rgb(249, 248, 255);\n"
"font: 22pt \"华文行楷\";")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 90, 81, 31))
        self.comboBox.setStyleSheet("background-color: rgb(152, 31, 50);\n"
"color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(30, 390, 941, 361))
        self.tableView.setObjectName("tableView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 140, 91, 31))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 9pt \"思源黑体 CN Medium\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 52, 135, 255), stop:1 rgba(18, 63, 149, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(60, 160, 121, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(200, 160, 121, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 160, 121, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(460, 160, 121, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(590, 160, 121, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(720, 160, 121, 21))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(60, 200, 121, 21))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(200, 200, 121, 21))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(330, 200, 121, 21))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(460, 200, 121, 21))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(720, 200, 121, 21))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(590, 200, 121, 21))
        self.checkBox_12.setObjectName("checkBox_12")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 10, 941, 61))
        self.plainTextEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(11, 61, 146, 255), stop:1 rgba(30, 39, 50, 255));")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 280, 91, 31))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 9pt \"思源黑体 CN Medium\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 101, 61, 255), stop:1 rgba(18, 63, 149, 255));\n"
"background-color: rgb(150, 39, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(60, 240, 121, 21))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(200, 240, 121, 21))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(330, 240, 121, 21))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_16.setGeometry(QtCore.QRect(460, 240, 121, 21))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_17.setGeometry(QtCore.QRect(590, 240, 121, 21))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_18.setGeometry(QtCore.QRect(200, 280, 121, 21))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_19.setGeometry(QtCore.QRect(330, 280, 121, 21))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_20.setGeometry(QtCore.QRect(460, 280, 121, 21))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_21.setGeometry(QtCore.QRect(590, 280, 121, 21))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_22.setGeometry(QtCore.QRect(720, 280, 121, 21))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_23.setGeometry(QtCore.QRect(720, 240, 121, 21))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_24.setGeometry(QtCore.QRect(60, 280, 121, 21))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_25.setGeometry(QtCore.QRect(60, 320, 121, 21))
        self.checkBox_25.setObjectName("checkBox_25")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 440, 521, 141))
        self.label_2.setStyleSheet("font: 10pt \"宋体\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(820, 110, 16, 16))
        self.pushButton_4.setStyleSheet("font: 8pt \"华文琥珀\";\n"
"color: rgb(136, 136, 136);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(880, 330, 91, 31))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 57 9pt \"思源黑体 CN Medium\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 101, 61, 255), stop:1 rgba(18, 63, 149, 255));\n"
"background-color: rgb(150, 39, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 831, 211))
        self.label_3.setStyleSheet("background-color: rgb(248, 248, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.plainTextEdit.raise_()
        self.pushButton.raise_()
        self.textEdit.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.tableView.raise_()
        self.pushButton_2.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.checkBox_9.raise_()
        self.checkBox_10.raise_()
        self.checkBox_11.raise_()
        self.checkBox_12.raise_()
        self.pushButton_3.raise_()
        self.checkBox_13.raise_()
        self.checkBox_14.raise_()
        self.checkBox_15.raise_()
        self.checkBox_16.raise_()
        self.checkBox_17.raise_()
        self.checkBox_18.raise_()
        self.checkBox_19.raise_()
        self.checkBox_20.raise_()
        self.checkBox_21.raise_()
        self.checkBox_22.raise_()
        self.checkBox_23.raise_()
        self.checkBox_24.raise_()
        self.checkBox_25.raise_()
        self.label_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_4.clicked.connect(self.textEdit.clear)
        self.pushButton_4.clicked.connect(self.tableView.clearSelection)
        self.pushButton_5.clicked.connect(MainWindow.close)
        self.pushButton_4.clicked.connect(self.label_2.clear)

        self.pushButton.clicked.connect(self.handler)
        self.pushButton_2.clicked.connect(self.updatas)
        self.checkBox.setChecked(True)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #检索按钮响应函数
    def handler(self):
        if self.checkBox.isChecked() == True:
            cs = self.checkBox.text()
        else:
            cs = []
            if self.checkBox_2.isChecked() == True:
                cs.append(self.checkBox_2.text())
            if self.checkBox_3.isChecked() == True:
                cs.append(self.checkBox_3.text())
            if self.checkBox_4.isChecked() == True:
                cs.append(self.checkBox_4.text())
            if self.checkBox_5.isChecked() == True:
                cs.append(self.checkBox_5.text())
            if self.checkBox_6.isChecked() == True:
                cs.append(self.checkBox_6.text())
            if self.checkBox_7.isChecked() == True:
                cs.append(self.checkBox_7.text())
            if self.checkBox_8.isChecked() == True:
                cs.append(self.checkBox_8.text())
            if self.checkBox_9.isChecked() == True:
                cs.append(self.checkBox_9.text())
            if self.checkBox_10.isChecked() == True:
                cs.append(self.checkBox_10.text())
            if self.checkBox_11.isChecked() == True:
                cs.append(self.checkBox_11.text())
            if self.checkBox_12.isChecked() == True:
                cs.append(self.checkBox_12.text())
            if self.checkBox_13.isChecked() == True:
                cs.append(self.checkBox_13.text())
            if self.checkBox_14.isChecked() == True:
                cs.append(self.checkBox_14.text())
            if self.checkBox_15.isChecked() == True:
                cs.append(self.checkBox_15.text())
            if self.checkBox_16.isChecked() == True:
                cs.append(self.checkBox_16.text())
            if self.checkBox_17.isChecked() == True:
                cs.append(self.checkBox_17.text())
            if self.checkBox_18.isChecked() == True:
                cs.append(self.checkBox_18.text())
            if self.checkBox_19.isChecked() == True:
                cs.append(self.checkBox_19.text())
            if self.checkBox_20.isChecked() == True:
                cs.append(self.checkBox_20.text())
            if self.checkBox_21.isChecked() == True:
                cs.append(self.checkBox_21.text())
            if self.checkBox_22.isChecked() == True:
                cs.append(self.checkBox_22.text())
            if self.checkBox_23.isChecked() == True:
                cs.append(self.checkBox_23.text())
            if self.checkBox_24.isChecked() == True:
                cs.append(self.checkBox_24.text())
            if self.checkBox_25.isChecked() == True:
                cs.append(self.checkBox_25.text())
        print(cs)
        key = self.comboBox.currentText()
        value = self.textEdit.toPlainText()
        df = news_sql.qy_sql(key, value, cs)
        model = dfshow.PdTable(df)
        if df.shape[0] == 0:
            t = '抱歉未找到您所需要的内容！'
        else:
            t = ''
        self.label_2.setText(t)
        self.tableView.setModel(model)

    #更新按钮响应函数
    def updatas(self):
        t = updata_news.AddisOnly()
        self.label_2.setText(t)
        df = pd.DataFrame(columns=['title','content', 'link', 'time'])
        model = dfshow.PdTable(df)
        self.tableView.setModel(model)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "搜索"))
        self.label.setText(_translate("MainWindow", "中国企业相关信息检索"))
        self.comboBox.setItemText(0, _translate("MainWindow", "标题"))
        self.comboBox.setItemText(1, _translate("MainWindow", "时间"))
        self.pushButton_2.setText(_translate("MainWindow", "更新"))
        self.checkBox.setText(_translate("MainWindow", "全部"))
        self.checkBox_2.setText(_translate("MainWindow", "企业风采"))
        self.checkBox_3.setText(_translate("MainWindow", "企业新闻"))
        self.checkBox_4.setText(_translate("MainWindow", "宏观经济"))
        self.checkBox_5.setText(_translate("MainWindow", "营业环境"))
        self.checkBox_6.setText(_translate("MainWindow", "企业文化"))
        self.checkBox_7.setText(_translate("MainWindow", "企业之家"))
        self.checkBox_8.setText(_translate("MainWindow", "企业管理"))
        self.checkBox_9.setText(_translate("MainWindow", "企业党建"))
        self.checkBox_10.setText(_translate("MainWindow", "产业经济"))
        self.checkBox_11.setText(_translate("MainWindow", "政商关系"))
        self.checkBox_12.setText(_translate("MainWindow", "涉企政策"))
        self.pushButton_3.setText(_translate("MainWindow", "企业招聘"))
        self.checkBox_13.setText(_translate("MainWindow", "峰会论坛"))
        self.checkBox_14.setText(_translate("MainWindow", "一带一路"))
        self.checkBox_15.setText(_translate("MainWindow", "园区建设"))
        self.checkBox_16.setText(_translate("MainWindow", "大学堂"))
        self.checkBox_17.setText(_translate("MainWindow", "涉企法规"))
        self.checkBox_18.setText(_translate("MainWindow", "500强要闻"))
        self.checkBox_19.setText(_translate("MainWindow", "500强排行"))
        self.checkBox_20.setText(_translate("MainWindow", "500强文化"))
        self.checkBox_21.setText(_translate("MainWindow", "500强故事"))
        self.checkBox_22.setText(_translate("MainWindow", "500强分析"))
        self.checkBox_23.setText(_translate("MainWindow", "主题论坛"))
        self.checkBox_24.setText(_translate("MainWindow", "平行论坛"))
        self.checkBox_25.setText(_translate("MainWindow", "美丽中国"))
        self.pushButton_4.setText(_translate("MainWindow", "×"))
        self.pushButton_5.setText(_translate("MainWindow", "退出"))

