# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\专业实训\程序实现\offer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import dfshow
import imgshow
import imgshow2
import spider_offer
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 80, 791, 41))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 80, 111, 31))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "font: 57 9pt \"思源黑体 CN Medium\";\n"
                                      "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 117, 34, 255), stop:1 rgba(237, 99, 17, 255));")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 10, 461, 41))
        self.label_4.setStyleSheet("color: rgb(249, 248, 255);\n"
                                   "font: 22pt \"华文行楷\";")
        self.label_4.setObjectName("label_4")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(40, 140, 791, 181))
        self.tableView.setObjectName("tableView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(790, 30, 171, 31))
        self.label_2.setStyleSheet("font: 10pt \"站酷高端黑\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(850, 340, 111, 31))
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "background-color: qlineargradient(spread:pad, x1:0.455, y1:0.727091, x2:1, y2:1, stop:0 rgba(243, 86, 97, 255), stop:1 rgba(197, 80, 139, 255));\n"
                                    "font: 7pt ;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(850, 220, 111, 31))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 57 9pt \"思源黑体 CN Medium\";\n"
                                        "background-color: rgb(243, 86, 97);\n"
                                        "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 260, 111, 31))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 57 9pt \"思源黑体 CN Medium\";\n"
                                        "background-color: rgb(243, 86, 97);\n"
                                        "")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(810, 100, 16, 16))
        self.pushButton_5.setStyleSheet("font: 8pt \"华文琥珀\";\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "color: rgb(136, 136, 136);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 340, 791, 411))
        self.label.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(850, 380, 111, 31))
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 57 9pt \"思源黑体 CN Medium\";\n"
                                        "background-color: rgb(243, 86, 97);\n"
                                        "")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 120, 111, 31))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 57 9pt \"思源黑体 CN Medium\";\n"
                                        "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 117, 34, 255), stop:1 rgba(237, 99, 17, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 0, 921, 61))
        self.label_3.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.232955, y1:0.466, x2:1, y2:0.630682, stop:0 rgba(250, 125, 29, 255), stop:1 rgba(197, 80, 139, 255));")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.textEdit.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.tableView.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()
        self.pushButton_7.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton_5.clicked.connect(self.textEdit.clear)
        self.pushButton_5.clicked.connect(self.tableView.clearSelection)
        self.pushButton_4.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.get_offer)
        self.pushButton_7.clicked.connect(self.openimage)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # 搜索按钮响应函数
    def get_offer(self):
        # 保存数据
        key = self.textEdit.toPlainText()
        df = spider_offer.new_data(key)
        model = dfshow.PdTable(df)
        self.tableView.setModel(model)

    def openimage(self):
        # 生成图片
        # cyshow.get_cyt()
        imgshow.again_get_img()
        imgshow2.again_get_img()

        imgkey = self.comboBox.currentText()
        # if imgkey == '词云图':
        #     # 通过cv读取图片
        #     # imgpath = 'cyt.png'
        if imgkey == '柱状图 折线图':
            imgpath = 'img1.png'
        else:
            imgpath = 'img2.png'
        try:
            img = QtGui.QPixmap(imgpath).scaled(791, 411)
            self.label.setPixmap(img)
            print('可视化成功！')
        except:
            print('生成失败')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "搜索"))
        self.label_4.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "企业招聘信息检索"))
        self.label_2.setText(_translate("MainWindow", "祝您前程无忧！"))
        self.comboBox.setItemText(0, _translate("MainWindow", "柱状图 折线图"))
        self.comboBox.setItemText(1, _translate("MainWindow", "词云图"))
        self.comboBox.setItemText(2, _translate("MainWindow", "饼图"))
        self.pushButton_3.setText(_translate("MainWindow", "返回原界面"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.pushButton_5.setText(_translate("MainWindow", "×"))
        self.pushButton_7.setText(_translate("MainWindow", "可视化"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))

